spring.datasource:
  url: jdbc:postgresql://localhost:5432/evaluation
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
  hikari:
    connection-timeout: 10000
    validation-timeout: 10000
    idle-timeout: 10000
    leak-detection-threshold: 10000
    max-lifetime: 3600000
    max-pool-size: 2
    min-idle: 1000
    is-auto-commit: false